### ISSUE TITLE
How to change the drawable of thumb and indicator.

### ISSUE THREAD

**Issue by ammysandhu** [AnderWeb/discreteSeekBar#42] opened 2015-08-05 15:30 UTC
Hi 
Good library.
but i want to change the drawable for Thumb and Indicator ( Progress BALLON when drag ). How can i change it ?
Thanks

**Comment by AnderWeb** [comment] 2016-01-29 11:10
duplicate of issue #39

**Closed by AnderWeb** 2016-01-29 11:10 UTC
